### ISSUE TITLE
Falsche Werteverarbeitung

### ISSUE THREAD

**Issue by intruder7777** [Chris-656/ioBroker.huum-sauna#19]
Hallo Chris,

ich schreibe jetzt nochmal hier da du scheinbar im Forum nicht soviel unterwegs bist ;-)
Ersteinmal vielen, vielen Dank für den Adapter. Ich nutze deinen Adapter seit knapp 6 Monaten mittlerweile mit einem sehr komplexen Skript. Was mir als Fehler aufgefallen ist, setzte ich die Targettemperataur in den Objekten mit dem AckFlag false, wird der Wert nicht bestätigt aber dafür taucht unter dem Objekt switchLight der Wert bestätigt auf.
b6b296a0-93db-4a72-8be5-ecef878057dc-image.png

das soll doch bestimmt nicht so sein.
setzte ich den Wert unter targetTemp mit ackflag true dann taucht er dort nicht auf.
Auch wird in beiden Varianten der Wert nicht übermittelt.( Die Änderung ist nicht in der App zu sehen)

Viele Grüße

![image](https://user-images.githubusercontent.com/45670139/215721953-8168f892-72fe-48a2-8383-7636341df40a.png)

**Comment by Chris-1965** [comment]
Hi,
Ich nehme an, dass deine Parameter bei LichtPfad leer sind du also das Licht der Sauna nutzt. Ich habe das Verhalten getestest und konnte es nachvollziehen. Ich habe einige Änderungen gemacht und werde gleich eine neue Version (0.4.3) machen. Bitte gleich testen und Feedback an mich zurück (hier). Im Forum bin ich eher  selten.
lG Chris

**Comment by intruder7777** [comment]
Hallo Chris, sorry für die späte Rückmeldung. Bin diese Woche nicht zuhause. Habs aber mal remote (VPN) getestet. Aktuell wirkt sich eine Veränderung der Target Temp zumindest nicht mehr auf §SwitchLight" aus. Wobei eine Änderung der TargetTemp im ioBroker keine Änderung in App bewirkt. Zumindest wenn die Sauna nicht eingeschaltet ist. 
Was meinst du mit Lichtpfad? Ich nutze aktuell nicht Steuerungsmöglich des Lichts über die HUUM Steuerung

LG

**Comment by Chris-1965** [comment]
Hi,
Ich habe mir das angesehen.
Es gibt nur die API
POST - api.huum.eu/action/home/start?targetTemperature=80

Damit änderst du die targettemp aber schaltest auch gleich die Sauna ein. Dies kann zu unerwünschten Ergebnissen führen wenn durch die Änderung gleich die Sauna angeht.
In der derzeitgen Version wird ja der Wert für target im State hinterlegt und bei einschalten der Saun verwendet.
lG Chris
________________________________
Von: intruder7777 ***@***.***>
Gesendet: Freitag, 3. Februar 2023 09:09
An: Chris-1965/ioBroker.huum-sauna ***@***.***>
Cc: Besterquester ***@***.***>; Comment ***@***.***>
Betreff: Re: [Chris-1965/ioBroker.huum-sauna] Falsche Werteverarbeitung (Issue #19)


Hallo Chris, sorry für die späte Rückmeldung. Bin diese Woche nicht zuhause. Habs aber mal remote (VPN) getestet. Aktuell wirkt sich eine Veränderung der Target Temp zumindest nicht mehr auf §SwitchLight" aus. Wobei eine Änderung der TargetTemp im ioBroker keine Änderung in App bewirkt. Zumindest wenn die Sauna nicht eingeschaltet ist.
Was meinst du mit Lichtpfad? Ich nutze aktuell nicht Steuerungsmöglich des Lichts über die HUUM Steuerung

LG

**Comment by intruder7777** [comment]
okay, top! das lass mal dann auch lieber so ;-)
Danke dir

**Comment by Chris-656** [comment]
ok schliesse den Issue dann 
lG Chris
