### ISSUE TITLE
targetTempReached funktion.

### ISSUE THREAD

**Issue by Alex18081** [Chris-656/ioBroker.huum-sauna#20]
Hi Chris,

Danke für die Umsetzung!

Habe bemerkt das state targetTempReached wieder auf "false" erst nach dem neu einschalten die Sauna wechselt. Währe es nicht sinnvoller bereits bei ausschalten die Sauna bzw. bei switchSauna = false das state targetTempReached auf "false" umschalten?

Und eventuell wird noch ein Korrektur State gebraucht die zusammen mit targetTempReached arbeitet. Hintergrund ist das wenn ein intelligenten Heizalgorithmus aktiviert ist, das eingestellte (gewünschte) Temperatur wird nie erreicht sondern bleibt ein paar grad darunter. Z.b. bei eingestellter 80° Soll Temperatur, wird Aktuelle Temperatur nicht höher als 78°.
Ich habe gedacht das wenn z.b. Korrektur State steht bei wert „0“ wird targetTempReached warten bis aktuelle Temperatur das Soll Temperatur erreicht und bei wert „2“ um zwei grad früher auf „true“ umschaltet.

MfG

Alex

**Comment by Chris-656** [comment]
Hi
ICh denke du meintest dass wenn die Sauna per App ausschaltest wird tempReached nicht auf false gesetzt. Denn aus der App wird das Flag für ein und aus gesetzt. Ich habe jetzt einmal auch deisen Fall integriert.

Zusätzlich gibt es die von dir gewünschten Offset für den intelligenten Modus der Sauna. Bitte testen und Feedbacvk.
Neue Version 0.4.4 auf git verfügbar
lG Chris
________________________________
Von: Alex ***@***.***>
Gesendet: Freitag, 10. Februar 2023 22:06
An: Chris-1965/ioBroker.huum-sauna ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Chris-1965/ioBroker.huum-sauna] targetTempReached funktion. (Issue #20)


Hi Chris,

Danke für die Umsetzung!

Habe bemerkt das state targetTempReached wieder auf "false" erst nach dem neu einschalten die Sauna wechselt. Währe es nicht sinnvoller bereits bei ausschalten die Sauna bzw. bei switchSauna = false das state targetTempReached auf "false" umschalten?

Und eventuell wird noch ein Korrektur State gebraucht die zusammen mit targetTempReached arbeitet. Hintergrund ist das wenn ein intelligenten Heizalgorithmus aktiviert ist, das eingestellte (gewünschte) Temperatur wird nie erreicht sondern bleibt ein paar grad darunter. Z.b. bei eingestellter 80° Soll Temperatur, wird Aktuelle Temperatur nicht höher als 78°.
Ich habe gedacht das wenn z.b. Korrektur State steht bei wert „0“ wird targetTempReached warten bis aktuelle Temperatur das Soll Temperatur erreicht und bei wert „2“ um zwei grad früher auf „true“ umschaltet.

MfG

Alex

**Comment by Alex18081** [comment]
Danke! Habe v.0.4.4 installiert und Offsetwert eingesetzt. Werde bei dem nächsten mal testen und berichten!

**Comment by Alex18081** [comment]
> Hi ICh denke du meintest dass wenn die Sauna per App ausschaltest wird tempReached nicht auf false gesetzt. Denn aus der App wird das Flag für ein und aus gesetzt. Ich habe jetzt einmal auch deisen Fall integriert. Zusätzlich gibt es die von dir gewünschten Offset für den intelligenten Modus der Sauna. Bitte testen und Feedbacvk. Neue Version 0.4.4 auf git verfügbar lG Chris
>

Hi. Gesterna konte ich testetn und hat alles perfekt funktioniert! Vielen Dank!

**Comment by Chris-656** [comment]
das klingt doch gut !
