### ISSUE TITLE
Absturz wenn keine Sauna im Account

### ISSUE THREAD

**Issue by fuchs-1978** [Chris-656/ioBroker.huum-sauna#27]
Ich habe einen vielleicht nicht typischen Anwendungsfall. Ich möchte meine Saunasteuerung tauschen und habe den Huum im Auge. Daher wollte ich mir vorab den Adapter ansehen, allerdings stürzt der Adapter dabei kontinuierlich ab. Vielleicht ist die Info hilfreich für ein Abfangen dieses Fehlers. Schöne Grüße und Danke für deine Mühe

<html>
<body>

huum-sauna.0 | 2023-10-29 10:59:54.950 | info | Logged in to HUUM User:c@htp-tel.de
-- | -- | -- | --
huum-sauna.0 | 2023-10-29 10:59:54.922 | info | starting. Version 0.4.4 in /opt/iobroker/node_modules/iobroker.huum-sauna, node: v18.17.1, js-controller: 5.0.15
host.iobroker0922 | 2023-10-29 10:59:52.889 | info | instance system.adapter.huum-sauna.0 started with pid 2372517
host.iobroker0922 | 2023-10-29 10:59:22.772 | info | Restart adapter system.adapter.huum-sauna.0 because enabled
host.iobroker0922 | 2023-10-29 10:59:22.772 | error | instance system.adapter.huum-sauna.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
huum-sauna.0 | 2023-10-29 10:59:22.652 | info | terminating
huum-sauna.0 | 2023-10-29 10:59:22.150 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
huum-sauna.0 | 2023-10-29 10:59:22.149 | info | terminating
huum-sauna.0 | 2023-10-29 10:59:22.102 | error | undefined is not a valid state value
huum-sauna.0 | 2023-10-29 10:59:22.101 | error | Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17) at HuumSauna._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49) at HuumSauna.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21) at HuumSauna.syncAppValues (/opt/iobroker/node_modules/iobroker.huum-sauna/main.js:164:8) at HuumSauna.getSaunaStatus (/opt/iobroker/node_modules/iobroker.huum-sauna/main.js:226:9) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
huum-sauna.0 | 2023-10-29 10:59:22.090 | error | unhandled promise rejection: undefined is not a valid state value
huum-sauna.0 | 2023-10-29 10:59:22.090 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
huum-sauna.0 | 2023-10-29 10:59:22.088 | info | HUUM Request: statusCode: 230 temperature:undefined targetTemp:undefined sethumidity:undefined Door closed:undefined Config:undefined light:undefined steamerError:undefined
huum-sauna.0 | 2023-10-29 10:59:21.937 | info | Adapter startet: c@htp-tel.de, Update every 60 seconds; StandBy Mode is set to : 10 Minutes
huum-sauna.0 | 2023-10-29 10:59:21.703 | info | Logged in to HUUM User:c@htp-tel.de
huum-sauna.0 | 2023-10-29 10:59:21.654 | info | starting. Version 0.4.4 in /opt/iobroker/node_modules/iobroker.huum-sauna, node: v18.17.1, js-controller: 5.0.15

</body>
</html>

**Comment by Chris-656** [comment]
OK try the new version from git (adapter install from git) and give me feedback if it works
regards Chris

**Comment by fuchs-1978** [comment]
I have installed the new version. It runs without crashes, but I still receive the following message:

<html>
<body>


huum-sauna.0 | 2023-10-30 09:01:22.645 | error | out Adapter Connection Error: TypeError: Cannot read properties of null (reading 'statusCode')
-- | -- | -- | --
huum-sauna.0 | 2023-10-30 09:01:22.644 | warn | Warning: Sauna Status: 230
huum-sauna.0 | 2023-10-30 09:01:21.472 | info | Adapter startet: creineke@htp-tel.de, Update every 60 seconds; StandBy Mode is set to : 10 Minutes
huum-sauna.0 | 2023-10-30 09:01:21.376 | info | Logged in to HUUM User:creineke@htp-tel.de
huum-sauna.0 | 2023-10-30 09:01:21.341 | info | starting. Version 0.4.4 (non-npm: Chris-656/ioBroker.huum-sauna) in /opt/iobroker/node_modules/iobroker.huum-sauna, node: v18.17.1, js-controller: 5.0.15


</body>
</html>

**Comment by Chris-656** [comment]
Should work with latest version 0.4.5
Please close with comment if everything is ok
regards Chris

**Comment by fuchs-1978** [comment]
I think now it is as expected, the message comes:

Warning: Sauna Status: Sauna ist Offline (230)


I have another question, do you have a humidity sensor on your sauna? Maybe you have a source of supply? Sorry for the offtopic question.

**Comment by Chris-656** [comment]
Please close this issue use
https://forum.iobroker.net/topic/51593/test-adapter-iobroker-huum-sauna-github-latest

regards Chris

**Comment by fuchs-1978** [comment]
Close
