### ISSUE TITLE
Falsche Beschriftung

### ISSUE THREAD

**Issue by fuchs-1978** [Chris-656/ioBroker.huum-sauna#29]
Ist diese Beschreibung korrekt? Hier taucht Steam zweimal auf, dry hingegen garnicht	

      "steamPresetHumidityhelper": {
		"en": "Humidity Value for the Steam Sauna Mode",
	},
	"steamPresetTemphelper": {
		"en": "Temperature  Value for the Steam Sauna Mode",
	},
	"**dry**PresetHumidityhelper": {
		"en": "Humidity Value for the **Steam Sauna Mode**",
	},
	"**dry**PresetTemphelper": {
		"en": "Temperature  Value for the **Steam Sauna Mode**",
	},

**Comment by Chris-656** [comment]
Danke,
Lust einen PR zu öffnen. lG Chris

**Comment by Chris-656** [comment]
Kein Problem, danke für die Infos, habe es bereits geändert. Pull Requests über GIT gehen eigentlich recht einfach, aber du müsstest dich natürlich einlesen.
lG Chris

**Comment by fuchs-1978** [comment]
Ich werde mich Mal belesen. LG
